#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := stdk_cts

EXTRA_COMPONENT_DIRS := ${IDF_PATH}/../../iot-core ${IDF_PATH}/../../iot-core/test/framework/cts

include $(IDF_PATH)/make/project.mk

