CONFIG_STDK_IOT_CORE=y
CONFIG_STDK_IOT_CORE_OS_SUPPORT_FREERTOS=y
CONFIG_STDK_IOT_CORE_BSP_SUPPORT_XMC4800=y
CONFIG_STDK_IOT_CORE_NET_XMC4800=y
CONFIG_STDK_IOT_CORE_EASYSETUP_HTTP=y
CONFIG_STDK_IOT_CORE_CRYPTO_SUPPORT_ED25519=y
CONFIG_STDK_IOT_CORE_EASYSETUP_HTTP_USE_SOCKET_API=y
CONFIG_STDK_IOT_CORE_USE_MBEDTLS=y
CONFIG_STDK_IOT_CORE_SECURITY_BACKEND_SOFTWARE=y
CONFIG_MEDTLS_USE_AFR_MEMORY=y

# Debug config
CONFIG_STDK_IOT_CORE_LOG_LEVEL_ERROR=y
CONFIG_STDK_IOT_CORE_LOG_LEVEL_WARN=y
CONFIG_STDK_IOT_CORE_LOG_LEVEL_INFO=y
CONFIG_STDK_IOT_CORE_LOG_LEVEL_DEBUG=y

ifeq ($(CONFIG_STDK_IOT_CORE),y)
	USR_CFG = -DCONFIG_STDK_IOT_CORE
endif
ifeq ($(CONFIG_STDK_IOT_CORE_OS_SUPPORT_FREERTOS),y)
	USR_CFG += -DCONFIG_STDK_IOT_CORE_OS_SUPPORT_FREERTOS
endif
ifeq ($(CONFIG_STDK_IOT_CORE_BSP_SUPPORT_XMC4800),y)
	USR_CFG += -DCONFIG_STDK_IOT_CORE_BSP_SUPPORT_XMC4800
endif
ifeq ($(CONFIG_STDK_IOT_CORE_NET_XMC4800),y)
	USR_CFG += -DCONFIG_STDK_IOT_CORE_NET_XMC4800
endif
ifeq ($(CONFIG_STDK_IOT_CORE_EASYSETUP_HTTP),y)
	USR_CFG += -DCONFIG_STDK_IOT_CORE_EASYSETUP_HTTP
endif
ifeq ($(CONFIG_STDK_IOT_CORE_CRYPTO_SUPPORT_ED25519),y)
	USR_CFG += -DCONFIG_STDK_IOT_CORE_CRYPTO_SUPPORT_ED25519
endif
ifeq ($(CONFIG_STDK_IOT_CORE_SECURITY_BACKEND_SOFTWARE),y)
	USR_CFG += -DCONFIG_STDK_IOT_CORE_SECURITY_BACKEND_SOFTWARE
endif
ifeq ($(CONFIG_MEDTLS_USE_AFR_MEMORY),y)
	USR_CFG += -DCONFIG_MEDTLS_USE_AFR_MEMORY
endif
ifeq ($(CONFIG_STDK_IOT_CORE_LOG_LEVEL_ERROR),y)
	USR_CFG += -DCONFIG_STDK_IOT_CORE_LOG_LEVEL_ERROR
endif
ifeq ($(CONFIG_STDK_IOT_CORE_LOG_LEVEL_WARN),y)
	USR_CFG += -DCONFIG_STDK_IOT_CORE_LOG_LEVEL_WARN
endif
ifeq ($(CONFIG_STDK_IOT_CORE_LOG_LEVEL_INFO),y)
	USR_CFG += -DCONFIG_STDK_IOT_CORE_LOG_LEVEL_INFO
endif
ifeq ($(CONFIG_STDK_IOT_CORE_LOG_LEVEL_DEBUG),y)
	USR_CFG += -DCONFIG_STDK_IOT_CORE_LOG_LEVEL_DEBUG
endif
ifeq ($(CONFIG_STDK_IOT_CORE_EASYSETUP_HTTP_USE_SOCKET_API),y)
	USR_CFG += -DCONFIG_STDK_IOT_CORE_EASYSETUP_HTTP_USE_SOCKET_API
endif
ifeq ($(CONFIG_STDK_IOT_CORE_USE_MBEDTLS),y)
	USR_CFG += -DCONFIG_STDK_IOT_CORE_USE_MBEDTLS
endif
